config/routes.rb
Rails.application.routes.draw do
  root 'home#geolocation'
  # post '/zipcode', to: 'home#zipcode'
  get '/zipcode', to: 'home#zipcode'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  require 'net/http'
  require 'json'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def geolocation
    if params[:lat_long].present?
      @lat_lang = params[:lat_long].split("|")
      weather_url =
          "http://api.openweathermap.org/data/2.5/weather?lat=#{@lat_lang[0]}&lon=#{@lat_lang[1]}&appid=#{Rails.application.credentials[:openweather][:API_KEY]}&units=imperial"
      @weather_output = JSON.parse(Net::HTTP.get(URI(weather_url)))
      forecast_url = "http://api.openweathermap.org/data/2.5/forecast?lat=#{@lat_lang[0]}&lon=#{@lat_lang[1]}&cnt=9&appid=#{Rails.application.credentials[:openweather][:API_KEY]}&units=imperial"
      @forecast_output = JSON.parse(Net::HTTP.get(URI(forecast_url)))
    end
  end

  def zipcode
    if params[:zipcode].present?
      weather_url =
          "http://api.openweathermap.org/data/2.5/weather?zip=#{params[:zipcode]},us&appid=#{Rails.application.credentials[:openweather][:API_KEY]}&units=imperial"
      @weather_output = JSON.parse(Net::HTTP.get(URI(weather_url)))
      forecast_url = "http://api.openweathermap.org/data/2.5/forecast?zip=#{params[:zipcode]},us&cnt=9&appid=#{Rails.application.credentials[:openweather][:API_KEY]}&units=imperial"
      @forecast_output = JSON.parse(Net::HTTP.get(URI(forecast_url)))
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/geolocation.html.erb
<% if @lat_lang.present? %>
  <%= render partial: 'shared/current_weather', locals: {current_weather: @weather_output} %>
  <%= render partial: 'shared/forecast', locals: {forecast: @forecast_output} %>
<% else %>
  <script>
      getLocation();
  </script>
<% end %>

app/views/home/zipcode.html.erb
<% if params[:zipcode].blank? %>
  <%= render partial: 'shared/error', locals: { error_message: 'please enter a valid US 5-digit zipcode'.capitalize} %>
<% elsif @weather_output['message'].present? %>
  <%= render partial: 'shared/error', locals: { error_message: @weather_output['message'].capitalize} %>
<% else %>
  <%= render partial: 'shared/current_weather', locals: {current_weather: @weather_output} %>
  <%= render partial: 'shared/forecast', locals: {forecast: @forecast_output} %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HowistheWeather</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/header' %>
    <div class="container-fluid">
      <%= render 'shared/error' %>
      <%= yield %>
    </div>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/shared/_current_weather.html.erb
<div id="current-weather" class="card text-center">
  <div class="card-header">
    Today's weather in <span class="city"><%= current_weather['name'] %>, <%= current_weather['sys']['country'] %></span> | <span class="date"><%= Time.at(current_weather['dt']).to_formatted_s(:long) %></span>
  </div>
  <div class="card-body">
    <h5 class="card-title">  <%= image_tag "http://openweathermap.org/img/w/" + (current_weather['weather'][0]['icon']).html_safe + ".png" %> <%= current_weather['main']['temp'] %> °F,  <%= current_weather['weather'][0]['main']%></h5>
    <p class="card-text"><span class="description"><%= current_weather['weather'][0]['description']%> | </span><span class="high">High: <%= current_weather['main']['temp_max'] %> °F</span> | <span class="high">Low: <%= current_weather['main']['temp_min'] %> °F</span></p>
    <!--      <a href="#forecast" class="btn btn-primary">Check out the weather forecast for the next 3 days.</a>-->
  </div>
  <div class="card-footer">
    <span class="pressure">Pressure: <%= current_weather['main']['pressure']%> hpa</span> | <span class="pressure"> Humidity: <%= current_weather['main']['humidity']%> %</span> | <span class="sunrise"> Sunrise: <%= Time.at(current_weather['sys']['sunrise']).to_formatted_s(:long) %></span> | <span class="sunset"> Sunset: <%= Time.at(current_weather['sys']['sunset']).to_formatted_s(:long) %></span>
  </div>
</div>

app/views/shared/_error.html.erb
<% error_message ||= '' %>

<div id="error-message" class="alert alert-danger <%= error_message.present? ? 'show' : 'hide' %>" role="alert"><%= error_message %></div>

app/views/shared/_footer.html.erb
<footer class="footer bg-dark">
  <div class="container">
    <span class="text-muted float-left">
      Made by Mohammad Rahber-E-Alam Raafa © 2019
    </span>
    <span class="text-muted float-right">
      Powered by <%= image_tag 'https://openweathermap.org/themes/openweathermap/assets/img/openweather-negative-logo-RGB.png', width: 128, height: 54 %>
    </span>
  </div>
</footer>

app/views/shared/_forecast.html.erb
<div id="forecast" class="card-columns">
  <% forecast['list'].each do |forecast| %>
    <div class="card h-100">
      <div class="card-header">
        <span class="date"><%= Time.at(forecast['dt']).strftime("%B %e, %Y, at %I:%M %p" ) %></span>
      </div>
      <div class="card-body">
        <h5 class="card-title"><%= image_tag "http://openweathermap.org/img/w/" + (forecast['weather'][0]['icon']).html_safe + ".png" %> <%= forecast['main']['temp'] %> °F,  <%= forecast['weather'][0]['main']%></h5>
        <p class="card-text"><span class="description"><%= forecast['weather'][0]['description']%> | </span><span class="high">High: <%= forecast['main']['temp_max'] %> °F</span> | <span class="high">Low: <%= forecast['main']['temp_min'] %> °F</span></p>
      </div>
      <div class="card-footer">
        <small class="text-muted">
          <span class="pressure">Pressure: <%= forecast['main']['pressure']%> hpa</span> | <span class="pressure"> Humidity: <%= forecast['main']['humidity']%> %</span>
        </small>
      </div>
    </div>
  <%end %>
</div>

app/views/shared/_header.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container text-center">
    <a class="nav-link" href="/"><h1 class="display-4">How is the weather<%=fa_icon "question", class:"fas" %></h1></a>
    <%= form_tag zipcode_path, class: 'col-lg-6 offset-lg-3', method: :get do  %>
      <div class="row justify-content-center">
        <%= text_field_tag 'zipcode', nil, placeholder: 'Enter 5-digit US zip code', class: "form-control mr-sm-2" %>
        <%= submit_tag 'Search', class: "btn btn-outline-secondary my-2 my-sm-0" %>
      </div>
    <% end %>
  </div>
</div>